package seed

import (
	"time"

	"github.com/Pachared/CodeBazaarApi/internal/models"
	"gorm.io/gorm"
)

func Seed(db *gorm.DB) error {
	var productCount int64
	if err := db.Model(&models.Product{}).Count(&productCount).Error; err != nil {
		return err
	}
	if productCount > 0 {
		return nil
	}

	now := time.Now()

	users := []models.User{
		{
			ID:                  "usr_buyer_demo",
			Name:                "ผู้ซื้อทดลอง",
			Email:               "buyer.demo@codebazaar.local",
			Role:                "buyer",
			Provider:            "google",
			IsMock:              true,
			PhoneNumber:         "0812345678",
			SavedCardHolderName: "Pachara Demo",
			SavedCardNumber:     "4111 1111 1111 1111",
			SavedCardExpiry:     "12/28",
			NotifyOrders:        true,
			NotifyMarketplace:   true,
			TimestampedModel:    models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "usr_seller_demo",
			Slug:                  "codebazaar-seller-demo",
			Name:                  "CodeBazaar Seller Demo",
			Email:                 "seller.demo@codebazaar.local",
			Role:                  "seller",
			Provider:              "google",
			IsMock:                true,
			PhoneNumber:           "0898765432",
			StoreName:             "CodeBazaar Seller Demo",
			BankName:              "ธนาคารกสิกรไทย",
			BankAccountNumber:     "123-4-56789-0",
			BankBookImageName:     "bank-book-demo.png",
			BankBookImageURL:      "https://example.com/bank-book-demo.png",
			IdentityCardImageName: "identity-card-demo.png",
			IdentityCardImageURL:  "https://example.com/identity-card-demo.png",
			NotifyOrders:          true,
			NotifyMarketplace:     true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_minimal_craft",
			Slug:              "minimal-craft",
			Name:              "Minimal Craft",
			Email:             "minimal-craft@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Minimal Craft",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_northframe",
			Slug:              "northframe",
			Name:              "Northframe",
			Email:             "northframe@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Northframe",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_frame_district",
			Slug:              "frame-district",
			Name:              "Frame District",
			Email:             "frame-district@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Frame District",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_studio_mellow",
			Slug:              "studio-mellow",
			Name:              "Studio Mellow",
			Email:             "studio-mellow@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Studio Mellow",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_avenue_mono",
			Slug:              "avenue-mono",
			Name:              "Avenue Mono",
			Email:             "avenue-mono@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Avenue Mono",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                "usr_seller_launch_ledger",
			Slug:              "launch-ledger",
			Name:              "Launch Ledger",
			Email:             "launch-ledger@codebazaar.local",
			Role:              "seller",
			Provider:          "google",
			IsMock:            true,
			StoreName:         "Launch Ledger",
			NotifyOrders:      true,
			NotifyMarketplace: true,
			TimestampedModel:  models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
	}

	if err := db.Create(&users).Error; err != nil {
		return err
	}

	products := []models.Product{
		{
			ID:                    "bazaar-market-core",
			SellerID:              "usr_seller_minimal_craft",
			AssetType:             "source-code",
			Status:                "publish",
			CategoryID:            "marketplace",
			Category:              "มาร์เก็ตเพลส",
			Title:                 "แกนระบบมาร์เก็ตเพลสแบบขาวดำ",
			Summary:               "ระบบหน้าร้านสำหรับขายซอร์สโค้ดและไฟล์ดิจิทัล พร้อมหน้าแสดงรายการสินค้า ผู้ขาย และรายละเอียดแพ็กเกจ.",
			FullDescription:       "ชุดโปรเจกต์นี้เหมาะสำหรับคนที่ต้องการเริ่มระบบ marketplace สำหรับขายซอร์สโค้ดหรือเทมเพลตในโทนขาวดำแบบพร้อมใช้งาน โดยมีทั้งหน้าแสดงรายการขาย หน้ารายละเอียดสินค้า ตะกร้า ระบบโปรไฟล์ และ flow ฝั่งผู้ขายรวมอยู่ในชุดเดียว ช่วยให้เริ่มต่อยอดเป็นระบบจริงได้ไวขึ้นมาก.",
			Price:                 2490,
			Rating:                4.9,
			Sales:                 142,
			Tags:                  []string{"พร้อมใช้", "Responsive", "ขายไฟล์ดิจิทัล"},
			Stack:                 []string{"React", "TypeScript", "MUI"},
			FeatureHighlights:     []string{"มีหน้ารายการขาย หน้ารายละเอียดสินค้า และ flow ตะกร้าอยู่ครบ", "รองรับทั้งบทบาทผู้ซื้อ ผู้ขาย และหน้าโปรไฟล์ในโปรเจกต์เดียว", "โครงสร้างไฟล์แยกเป็นหมวดพร้อมต่อ backend และระบบชำระเงินจริง"},
			IncludedItems:         []string{"ซอร์สโค้ด React + TypeScript + MUI ทั้งชุด", "หน้าหลัก ค้นหา กรอง รายละเอียดสินค้า ตะกร้า และ checkout", "ตัวอย่าง service, type และ mock data สำหรับต่อ API จริง"},
			IdealFor:              []string{"ทีมที่ต้องการเริ่มเว็บขาย source code หรือ template", "ฟรีแลนซ์หรือสตูดิโอที่รับทำระบบขายไฟล์ดิจิทัล", "ผู้ขายที่อยากได้ base project สำหรับต่อยอดต่อทันที"},
			SupportInfo:           "เหมาะกับการนำไปต่อ payment gateway, ระบบอนุมัติผู้ขาย และระบบดาวน์โหลดจริงในภายหลัง",
			VersionLabel:          "v1.4",
			FileFormatLabel:       "ZIP + เอกสารประกอบ",
			UpdatedDaysAgo:        2,
			Delivery:              "ดาวน์โหลดได้ทันที",
			License:               "ใช้งานเชิงพาณิชย์",
			LicenseID:             "commercial",
			Verified:              true,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "glass-admin-th",
			SellerID:              "usr_seller_northframe",
			AssetType:             "source-code",
			Status:                "publish",
			CategoryID:            "dashboard",
			Category:              "แดชบอร์ด",
			Title:                 "แดชบอร์ดผู้ขายกระจกขาวดำ",
			Summary:               "ชุดหน้าจอจัดการสินค้า ออเดอร์ และรายได้ของผู้ขายในโทนกระจกขาวดำ พร้อมคอมโพเนนต์สถิติและตาราง.",
			FullDescription:       "แดชบอร์ดชุดนี้ออกแบบมาสำหรับระบบหลังบ้านของผู้ขายที่ต้องการดูภาพรวมสินค้า คำสั่งซื้อ รายได้ และการแจ้งเตือนในรูปแบบที่อ่านง่าย เน้นเลย์เอาต์ที่ชัดและใช้งานได้ต่อจริง เหมาะสำหรับใช้คู่กับ marketplace หรือระบบขายไฟล์ดิจิทัลที่ต้องมีหน้าจัดการหลังบ้านแยก.",
			Price:                 1890,
			Rating:                4.8,
			Sales:                 96,
			Tags:                  []string{"Admin", "Seller", "Analytics"},
			Stack:                 []string{"React", "MUI", "Charts"},
			FeatureHighlights:     []string{"มีชุดหน้าจอสรุปยอดขาย คำสั่งซื้อ และรายได้ของผู้ขาย", "เหมาะกับงานหลังบ้านที่ต้องใช้ตาราง สถิติ และกรองข้อมูลจำนวนมาก", "ดีไซน์โทนขาวดำแนว glass ที่เข้ากับหน้าบ้านของระบบเดียวกัน"},
			IncludedItems:         []string{"หน้าสรุปสถิติผู้ขายพร้อม card และ chart", "หน้ารายการออเดอร์และตารางจัดการสินค้า", "คอมโพเนนต์ dashboard พร้อมตัวอย่างข้อมูลสำหรับต่อ API"},
			IdealFor:              []string{"เจ้าของแพลตฟอร์มที่ต้องการหน้าหลังบ้านสำหรับผู้ขาย", "ทีมที่กำลังทำระบบ seller dashboard แยกจากหน้าร้าน", "โปรเจกต์ที่ต้องการเริ่มจาก UI สำเร็จรูปแล้วต่อ logic ภายหลัง"},
			SupportInfo:           "สามารถนำไปเชื่อม analytics, seller payout และระบบจัดการคำสั่งซื้อได้ต่อเนื่อง",
			VersionLabel:          "v1.2",
			FileFormatLabel:       "ZIP + Dashboard Assets",
			UpdatedDaysAgo:        5,
			Delivery:              "รวมไฟล์ต้นฉบับ",
			License:               "ใช้งานส่วนตัว",
			LicenseID:             "personal",
			Verified:              true,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "mono-launch-kit",
			SellerID:              "usr_seller_frame_district",
			AssetType:             "template",
			Status:                "publish",
			CategoryID:            "landing-page",
			Category:              "หน้าเปิดตัว",
			Title:                 "หน้าเปิดตัวสินค้าแบบมินิมอล",
			Summary:               "หน้าเปิดตัวสำหรับขาย source code หรือ template ที่เน้นลำดับข้อมูลชัด อ่านง่าย และพาไปยังหน้าซื้อได้เร็ว.",
			FullDescription:       "เทมเพลตหน้าเปิดตัวชุดนี้เหมาะสำหรับโปรโมตสินค้าดิจิทัลแบบหน้าเดียว โดยเน้นลำดับเนื้อหาให้ตัดสินใจเร็ว ตั้งแต่จุดขาย ฟีเจอร์ แพ็กเกจราคา ไปจนถึงปุ่มซื้อหรือปุ่มดูรายละเอียด เหมาะสำหรับใช้เป็น landing page ของ source code, UI kit หรือ productized service.",
			Price:                 1290,
			Rating:                4.7,
			Sales:                 184,
			Tags:                  []string{"Hero", "Premium", "Marketing"},
			Stack:                 []string{"React", "Motion", "MUI"},
			FeatureHighlights:     []string{"ลำดับ section ถูกจัดมาเพื่อปิดการขายและพาไปสู่ปุ่มซื้อได้เร็ว", "เหมาะกับงานโปรโมต source code, template และ digital product แบบหน้าเดียว", "องค์ประกอบภาพรวมเน้นความมินิมอล อ่านง่าย และปรับแบรนด์ต่อสะดวก"},
			IncludedItems:         []string{"หน้าเปิดตัวแบบ single page พร้อม section หลักครบ", "ชุด hero, feature, pricing และ call-to-action พร้อมใช้งาน", "ตัวอย่างข้อความและจังหวะ layout สำหรับสินค้าดิจิทัล"},
			IdealFor:              []string{"ผู้ขายที่ต้องการหน้า landing สำหรับโปรโมตสินค้าแบบเร็ว", "เอเจนซีที่ต้องทำหน้าเปิดตัวให้ลูกค้าในเวลาไม่มาก", "คนที่อยากได้ base page สำหรับแคมเปญเปิดขายสินค้าใหม่"},
			SupportInfo:           "เหมาะสำหรับต่อระบบฟอร์มลงทะเบียน ปุ่มซื้อ และ analytics สำหรับติดตาม conversion",
			VersionLabel:          "v1.1",
			FileFormatLabel:       "ZIP + Landing Sections",
			UpdatedDaysAgo:        1,
			Delivery:              "ติดตั้งได้ใน 1 ขั้นตอน",
			License:               "ใช้งานเชิงพาณิชย์",
			LicenseID:             "commercial",
			Verified:              false,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "thai-saas-starter",
			SellerID:              "usr_seller_studio_mellow",
			AssetType:             "source-code",
			Status:                "publish",
			CategoryID:            "saas",
			Category:              "SaaS เริ่มต้น",
			Title:                 "SaaS Starter ภาษาไทย",
			Summary:               "โครง SaaS เริ่มต้นที่มีหน้าแพ็กเกจ สมัครสมาชิก บทความ และหน้าจัดการบัญชีในภาษาไทยแบบครบ flow.",
			FullDescription:       "SaaS starter ภาษาไทยชุดนี้เหมาะสำหรับทีมที่อยากเริ่มระบบ subscription หรือ web application ที่มี flow ผู้ใช้ชัดเจน ตั้งแต่หน้าราคา สมัครสมาชิก เข้าระบบ โปรไฟล์ ไปจนถึงพื้นที่หลังบ้านเบื้องต้น โครงโดยรวมถูกวางมาเพื่อให้ต่อยอดทั้งฝั่งการตลาดและฝั่ง product ได้สะดวก.",
			Price:                 3290,
			Rating:                4.9,
			Sales:                 64,
			Tags:                  []string{"SaaS", "ไทย", "สมาชิก"},
			Stack:                 []string{"React", "TypeScript", "API Ready"},
			FeatureHighlights:     []string{"มี flow ผู้ใช้ครบตั้งแต่หน้าแพ็กเกจ สมัครสมาชิก ไปจนถึงพื้นที่บัญชี", "ภาษาไทยทั้งระบบ ช่วยลดเวลาปรับ copy สำหรับตลาดไทย", "เหมาะกับงานที่ต้องต่อระบบสมาชิก การชำระเงิน และสิทธิ์ใช้งานภายหลัง"},
			IncludedItems:         []string{"หน้า pricing, auth, profile และหน้าจัดการบัญชี", "โครงหน้า marketing และพื้นที่ใช้งานหลังล็อกอิน", "service และ type สำหรับต่อ backend หรือ subscription flow"},
			IdealFor:              []string{"ทีมสตาร์ตอัปที่อยากเริ่ม SaaS เป็นภาษาไทย", "นักพัฒนาที่ต้องการ starter project สำหรับระบบสมาชิก", "เจ้าของผลิตภัณฑ์ที่อยากเปิด MVP ให้เร็วที่สุด"},
			SupportInfo:           "เหมาะกับการเชื่อม auth จริง, payment gateway และระบบสิทธิ์แบบรายแพ็กเกจ",
			VersionLabel:          "v2.0",
			FileFormatLabel:       "ZIP + Starter Modules",
			UpdatedDaysAgo:        7,
			Delivery:              "ดาวน์โหลดได้ทันที",
			License:               "ขายต่อได้",
			LicenseID:             "resale",
			Verified:              true,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "ui-system-black",
			SellerID:              "usr_seller_avenue_mono",
			AssetType:             "component-kit",
			Status:                "publish",
			CategoryID:            "design-system",
			Category:              "ระบบดีไซน์",
			Title:                 "ระบบดีไซน์ขาวดำสำหรับโปรเจกต์ดิจิทัล",
			Summary:               "ชุด UI token, form, table, card, และ navigation โทนขาวดำพร้อมแนวทางการใช้งานในโปรเจกต์จริง.",
			FullDescription:       "ระบบดีไซน์ชุดนี้รวมองค์ประกอบหลักที่ใช้บ่อยในงานดิจิทัลไว้ครบ ทั้ง token, form, button, card, table และ navigation โดยยังคุมโทนขาวดำแบบเดียวกันทั้งระบบ ช่วยให้เริ่มโปรเจกต์ใหม่ได้ไวและรักษาความสม่ำเสมอของ UI ได้ง่ายขึ้น.",
			Price:                 1590,
			Rating:                4.6,
			Sales:                 88,
			Tags:                  []string{"UI Kit", "System", "Token"},
			Stack:                 []string{"MUI", "Figma Ready", "TypeScript"},
			FeatureHighlights:     []string{"รวม token และ component พื้นฐานสำหรับเริ่มระบบ UI อย่างเป็นระเบียบ", "เหมาะกับทีมที่ต้องการคุมมาตรฐานหน้าตาของหลายหน้าจอในทิศทางเดียวกัน", "ช่วยลดเวลาสร้าง form, table และ layout ซ้ำในแต่ละโปรเจกต์"},
			IncludedItems:         []string{"ชุด component พื้นฐาน เช่น button, input, card, table และ chip", "แนวทางโครงสร้าง design token และ style usage", "ตัวอย่างหน้าใช้งานจริงที่หยิบ component ไปประกอบต่อได้"},
			IdealFor:              []string{"ทีมที่กำลังเริ่ม design system ของตัวเอง", "โปรเจกต์ที่ต้องการ UI base ให้ต่อยอดได้หลายหน้า", "นักออกแบบและนักพัฒนาที่อยากได้ชุด component พร้อมใช้งาน"},
			SupportInfo:           "เหมาะสำหรับต่อยอดทั้งในงาน production UI และงาน internal tool ที่ต้องการคุมมาตรฐาน",
			VersionLabel:          "v1.8",
			FileFormatLabel:       "ZIP + UI Kit Files",
			UpdatedDaysAgo:        10,
			Delivery:              "รวมเอกสารการใช้งาน",
			License:               "ใช้งานส่วนตัว",
			LicenseID:             "personal",
			Verified:              true,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:                    "seller-onboarding-flow",
			SellerID:              "usr_seller_launch_ledger",
			AssetType:             "template",
			Status:                "publish",
			CategoryID:            "marketplace",
			Category:              "มาร์เก็ตเพลส",
			Title:                 "เส้นทางสมัครผู้ขาย",
			Summary:               "หน้าสมัครผู้ขาย ยืนยันข้อมูล และ onboarding checklist สำหรับ marketplace ที่ต้องการเปิดบัญชีขายแบบเป็นระบบ.",
			FullDescription:       "ชุดหน้าจอนี้เหมาะสำหรับระบบ marketplace ที่ต้องการจัดการการสมัครผู้ขายให้เป็นขั้นตอนมากขึ้น ตั้งแต่การเริ่มต้นสมัคร ยืนยันข้อมูล กรอกเอกสาร ไปจนถึง checklist สำหรับเปิดร้าน ช่วยให้ flow onboarding ดูมีระบบและพร้อมต่อ backend อนุมัติผู้ขายได้ง่ายขึ้น.",
			Price:                 2190,
			Rating:                4.8,
			Sales:                 51,
			Tags:                  []string{"Seller", "Onboarding", "Checklist"},
			Stack:                 []string{"React", "Forms", "MUI"},
			FeatureHighlights:     []string{"มี flow สมัครผู้ขาย ยืนยันข้อมูล และเช็กความพร้อมก่อนเปิดขาย", "เหมาะกับ marketplace ที่ต้องมีขั้นตอน onboarding แยกจากผู้ซื้อทั่วไป", "ช่วยลดเวลาวางโครงหน้ากรอกข้อมูลและ action ของฝั่งผู้ขาย"},
			IncludedItems:         []string{"หน้าสมัครผู้ขายและฟอร์มเก็บข้อมูลเบื้องต้น", "ขั้นตอน onboarding และ checklist ก่อนเปิดร้าน", "ตัวอย่างสถานะเอกสารและข้อความแนะนำผู้ขาย"},
			IdealFor:              []string{"แพลตฟอร์มที่ต้องการระบบสมัครผู้ขายแบบเป็นขั้นตอน", "ทีมที่กำลังทำ seller onboarding แยกจาก buyer auth", "โปรเจกต์ที่ต้องการเพิ่มความน่าเชื่อถือให้ฝั่งผู้ขาย"},
			SupportInfo:           "สามารถนำไปต่อระบบอนุมัติผู้ขาย อัปโหลดเอกสาร และการแจ้งสถานะได้ต่อทันที",
			VersionLabel:          "v1.3",
			FileFormatLabel:       "ZIP + Onboarding Screens",
			UpdatedDaysAgo:        3,
			Delivery:              "รวม source และ flow",
			License:               "ใช้งานเชิงพาณิชย์",
			LicenseID:             "commercial",
			Verified:              true,
			InstantDelivery:       true,
			SourceIncluded:        true,
			DocumentationIncluded: true,
			TimestampedModel:      models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
	}

	if err := db.Create(&products).Error; err != nil {
		return err
	}

	orders := []models.Order{
		{
			ID:               "ord_seed_001",
			OrderNumber:      "CB-55018324",
			BuyerID:          "usr_buyer_demo",
			CustomerName:     "อานนท์ พิชิตชัย",
			CustomerEmail:    "anont.dev@example.com",
			CustomerPhone:    "0891112233",
			PaymentMethod:    "promptpay",
			Subtotal:         2190,
			Total:            2190,
			Status:           "paid",
			PurchasedAt:      time.Date(2026, 4, 14, 10, 40, 0, 0, time.UTC),
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "ord_seed_002",
			OrderNumber:      "CB-55018402",
			BuyerID:          "usr_buyer_demo",
			CustomerName:     "ปาล์ม รัตนกร",
			CustomerEmail:    "palm.studio@example.com",
			CustomerPhone:    "0892223344",
			PaymentMethod:    "card",
			Subtotal:         2490,
			Total:            2490,
			Status:           "paid",
			PurchasedAt:      time.Date(2026, 4, 13, 4, 20, 0, 0, time.UTC),
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "ord_seed_003",
			OrderNumber:      "CB-55018517",
			BuyerID:          "usr_buyer_demo",
			CustomerName:     "มะปราง ชลธิชา",
			CustomerEmail:    "maprang.product@example.com",
			CustomerPhone:    "0893334455",
			PaymentMethod:    "bank-transfer",
			Subtotal:         2490,
			Total:            2490,
			Status:           "pending",
			PurchasedAt:      time.Date(2026, 4, 12, 7, 15, 0, 0, time.UTC),
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "ord_seed_004",
			OrderNumber:      "CB-56000001",
			BuyerID:          "usr_buyer_demo",
			CustomerName:     "ผู้ซื้อทดลอง",
			CustomerEmail:    "buyer.demo@codebazaar.local",
			CustomerPhone:    "0812345678",
			PaymentMethod:    "card",
			Subtotal:         3780,
			Total:            3780,
			Status:           "paid",
			PurchasedAt:      time.Date(2026, 4, 15, 9, 30, 0, 0, time.UTC),
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
	}

	if err := db.Create(&orders).Error; err != nil {
		return err
	}

	orderItems := []models.OrderItem{
		{
			ID:               "item_seed_001",
			OrderID:          "ord_seed_001",
			ProductID:        "seller-onboarding-flow",
			SellerID:         "usr_seller_launch_ledger",
			Title:            "เส้นทางสมัครผู้ขาย",
			Category:         "มาร์เก็ตเพลส",
			AuthorName:       "Launch Ledger",
			Price:            2190,
			License:          "ใช้งานเชิงพาณิชย์",
			DeliveryLabel:    "ดาวน์โหลดได้ทันที",
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "item_seed_002",
			OrderID:          "ord_seed_002",
			ProductID:        "bazaar-market-core",
			SellerID:         "usr_seller_minimal_craft",
			Title:            "แกนระบบมาร์เก็ตเพลสแบบขาวดำ",
			Category:         "มาร์เก็ตเพลส",
			AuthorName:       "Minimal Craft",
			Price:            2490,
			License:          "ใช้งานเชิงพาณิชย์",
			DeliveryLabel:    "ดาวน์โหลดได้ทันที",
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "item_seed_003",
			OrderID:          "ord_seed_003",
			ProductID:        "bazaar-market-core",
			SellerID:         "usr_seller_minimal_craft",
			Title:            "แกนระบบมาร์เก็ตเพลสแบบขาวดำ",
			Category:         "มาร์เก็ตเพลส",
			AuthorName:       "Minimal Craft",
			Price:            2490,
			License:          "ใช้งานเชิงพาณิชย์",
			DeliveryLabel:    "ดาวน์โหลดได้ทันที",
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "item_seed_004",
			OrderID:          "ord_seed_004",
			ProductID:        "bazaar-market-core",
			SellerID:         "usr_seller_minimal_craft",
			Title:            "แกนระบบมาร์เก็ตเพลสแบบขาวดำ",
			Category:         "มาร์เก็ตเพลส",
			AuthorName:       "Minimal Craft",
			Price:            2490,
			License:          "ใช้งานเชิงพาณิชย์",
			DeliveryLabel:    "ดาวน์โหลดได้ทันที",
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "item_seed_005",
			OrderID:          "ord_seed_004",
			ProductID:        "mono-launch-kit",
			SellerID:         "usr_seller_frame_district",
			Title:            "หน้าเปิดตัวสินค้าแบบมินิมอล",
			Category:         "หน้าเปิดตัว",
			AuthorName:       "Frame District",
			Price:            1290,
			License:          "ใช้งานเชิงพาณิชย์",
			DeliveryLabel:    "ติดตั้งได้ใน 1 ขั้นตอน",
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
	}

	if err := db.Create(&orderItems).Error; err != nil {
		return err
	}

	downloads := []models.DownloadItem{
		{
			ID:               "dl_seed_001",
			UserID:           "usr_buyer_demo",
			OrderID:          "CB-56000001",
			OrderItemID:      "item_seed_004",
			ProductID:        "bazaar-market-core",
			Title:            "แกนระบบมาร์เก็ตเพลสแบบขาวดำ",
			Category:         "มาร์เก็ตเพลส",
			AuthorName:       "Minimal Craft",
			Price:            2490,
			License:          "ใช้งานเชิงพาณิชย์",
			PaymentMethod:    "card",
			PurchasedAt:      time.Date(2026, 4, 15, 9, 30, 0, 0, time.UTC),
			Status:           "ready",
			VersionLabel:     "v1.4",
			FileName:         "codebazaar-bazaar-market-core-package.zip",
			FileSizeLabel:    "15 MB",
			DownloadsCount:   1,
			LastDownloadedAt: timePointer(time.Date(2026, 4, 16, 8, 0, 0, 0, time.UTC)),
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
		{
			ID:               "dl_seed_002",
			UserID:           "usr_buyer_demo",
			OrderID:          "CB-56000001",
			OrderItemID:      "item_seed_005",
			ProductID:        "mono-launch-kit",
			Title:            "หน้าเปิดตัวสินค้าแบบมินิมอล",
			Category:         "หน้าเปิดตัว",
			AuthorName:       "Frame District",
			Price:            1290,
			License:          "ใช้งานเชิงพาณิชย์",
			PaymentMethod:    "card",
			PurchasedAt:      time.Date(2026, 4, 15, 9, 30, 0, 0, time.UTC),
			Status:           "ready",
			VersionLabel:     "v1.1",
			FileName:         "codebazaar-mono-launch-kit-package.zip",
			FileSizeLabel:    "8 MB",
			DownloadsCount:   0,
			TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
		},
	}

	if err := db.Create(&downloads).Error; err != nil {
		return err
	}

	consent := models.CookieConsent{
		ID:               "cookie_seed_001",
		UserID:           "usr_buyer_demo",
		Status:           "all",
		Preferences:      models.CookiePreferences{Necessary: true, Preferences: true, Analytics: true, Marketing: true},
		ConsentUpdatedAt: now,
		TimestampedModel: models.TimestampedModel{CreatedAt: now, UpdatedAt: now},
	}

	return db.Create(&consent).Error
}

func timePointer(value time.Time) *time.Time {
	return &value
}
